const journalArticles = [
    {
        title: "Slat Cove Dynamics of Low Reynolds Number Flow Past a 30P30N High Lift Configuration",
        authors: "Vadsola, M., Agbaglah, G. and Mavriplis, C.",
        journal: "Physics of Fluids",
        volume: "33",
        issue: "3",
        year: "2021",
        pages: "033607",
        notes: null,
        url: "https://doi.org/10.1063/5.0036088",
        keywords: [7, 9, 10, 13, 11],
    },
    {
        title: "Designing to Engineer a Safer World",
        authors: "Mujawamariya, D., Fournier, J., Adatia, S. and Mavriplis, C.",
        journal: "Technology and Engineering Teacher",
        volume: "to appear",
        issue: null,
        year: "2020",
        pages: null,
        url: "#",
        keywords: [9, 5, 6, 2],
    },
    {
        title: "A Parallel hp-Adaptive High Order Discontinuous Galerkin Method for the Incompressible Navier-Stokes Equations",
        authors: "Chalmers, N., Agbaglah, G., Chrust, M. and Mavriplis, C.",
        journal: "Journal of Computational Physics: X",
        volume: "2",
        issue: null,
        year: "2019",
        pages: "100023",
        url: "https://doi.org/10.1016/j.jcpx.2019.100023",
        keywords: [7, 12, 9, 10, 13, 14],
    },
    {
        title: "Knitting Theory in STEM Performance Stories: Experiences in Developing a Performance Framework",
        authors:
            "Whynot, J., Mavriplis, C., Shannon, L., Farenhorst, A., Langelier, E. & Franz-Odendaal, T.",
        journal: "Canadian Journal of Program Evaluation",
        volume: "33",
        issue: "3",
        year: "2019",
        pages: "354-374",
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "Three-dimensional wakes behind cylinders of square and circular cross-section: early and long-time dynamics",
        authors: "G. Agbaglah and C. Mavriplis",
        journal: "Journal of Fluid Mechanics",
        volume: "870",
        issue: null,
        year: "2019",
        pages: "419-432",
        url: "https://doi.10.1017/jfm.2019.265",
        keywords: [7, 8, 9, 10, 11],
    },
    {
        title: "Le génie au-delà du vernis à ongle: mettre les questions d’intérêts féminins à l’avant plan",
        authors: "Mujawamariya, D., Fournier, J. et Mavriplis, C.",
        journal: "Spectre",
        volume: "48",
        issue: "3",
        year: "2019",
        pages: null,
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "Du génie des femmes pour des femmes? Voix d'ingénieurEs et de futurEs ingénieurEs",
        authors: "Mujawamariya, D. et Mavriplis, C.",
        journal: "Spectre",
        volume: "46",
        issue: "3",
        year: "2017",
        pages: null,
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "Women's Startup Network: Increasing Entrepreneurial Intent and Self-Efficacy for Female STEM Students",
        authors: "Elliott, C., Mavriplis, C. and Anis, H.",
        journal: "International Entrepreneurship and Management Journal",
        volume: null,
        issue: null,
        year: "2017",
        pages: null,
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "An Automated Method for Dynamic Red Blood Cell Aggregate Detection in Microfluidic Flow",
        authors: "Mehri, R., Niazi, E., Mavriplis, C. and Fenech, M.",
        journal: "Physiological Measurement",
        volume: "13",
        issue: null,
        year: "2017",
        pages: "01NT02",
        url: "#",
        keywords: [15, 7, 9],
    },
    {
        title: "Computational analysis of physical mechanisms at the onset of three-dimensionality in the wake of a square cylinder",
        authors: "Agbaglah, G. and Mavriplis, C.",
        journal: "Journal of Fluid Mechanics",
        volume: "833",
        issue: null,
        year: "2017",
        pages: "631-674",
        url: "#",
        keywords: [7, 8, 9, 10, 13],
    },
    {
        title: "Le génie des femmes au service des femmes: vers un enseignement équitable du génie",
        authors: "Mujawamariya, D. et Mavriplis, C.",
        journal: "Spectre",
        volume: "46",
        issue: "1",
        year: "2016",
        pages: "38-42",
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "Initiatives to Empower Women Faculty Members at the University of Ottawa: Mothers See the Value in Participation",
        authors: "Moreau-Johnson, F. and Mavriplis, C.",
        journal:
            "Journal of Motherhood, Special Issue: Supporting and Empowering Mothers in the Academe: Strategies for Institutional Change and Individual Agency",
        volume: "6",
        issue: "2",
        year: "2015",
        pages: "179-191",
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        title: "Direct Numerical Simulation of the Flow Around a Wall-Mounted Square Cylinder Under Various Inflow Conditions",
        authors:
            "Vinuesa, R., Schlatter, P., Malm, J., Mavriplis, C. and Henningson, D.S.",
        journal: "Journal of Turbulence",
        volume: "16",
        issue: "6",
        year: "2015",
        pages: "555-587",
        url: "#",
        keywords: [7, 12, 9, 10, 11],
    },
    {
        title: "Controlled Microfluidic Environment for Dynamic Investigation of Red Blood Cell Aggregation",
        authors: "Mehri, R., Mavriplis, C. and Fenech, M.",
        journal: "Journal of Visualized Experiments",
        volume: "100",
        issue: null,
        year: "2015",
        pages: null,
        url: "http://dx.doi.org/10.3791/52719",
        keywords: [15, 9, 10],
    },
    {
        title: "Investigation of Blood Flow Analysis and Red Blood Cell Aggregation",
        authors: "Mehri, R., Laplante, J., Mavriplis, C. and Fenech, M.",
        journal: "Journal of Medical and Biological Engineering",
        volume: "34",
        issue: "5",
        year: "2014",
        pages: "469-474",
        url: "http://dx.doi.org/10.5405/jmbe.1695",
        keywords: [15, 7, 9, 10],
    },
    {
        title: "Design of a Microfluidic System for Red Blood Cell Aggregation Investigation",
        authors: "Mehri, R., Mavriplis, C. and Fenech, M.",
        journal: "Journal of Medical and Biological Engineering",
        volume: "136",
        issue: "6",
        year: "2014",
        pages: "064501-064501-5",
        url: "#",
        keywords: [15, 7, 9, 10],
    },
    {
        title: "Computer Animation Challenges for Computational Fluid Dynamics",
        authors: "Vines, M., Lee, W.-S. and Mavriplis, C.",
        journal: "International Journal of Computational Fluid Dynamics",
        volume: "26",
        issue: "6-8",
        year: "2012",
        pages: "407-434",
        url: "#",
        keywords: [7, 9, 10],
    },
    {
        title: "Nonlinear Receptivity to Oblique Vortical Modes in Flow Past an Elliptic Leading Edge",
        authors:
            "Schrader, L.-U., Brandt, L., Mavriplis, C. and Henningson, D.",
        journal: "Journal of Turbulence",
        volume: "13",
        issue: "25",
        year: "2012",
        pages: "1-16",
        url: "#",
        keywords: [7, 8, 9, 10, 11],
    },
    {
        title: "Micro-particle image velocimetry measurement of blood flow: Validation and analysis of data pre-processing and processing methods",
        authors: "Pitts, K.L., Mehri, R., Mavriplis, C. and Fenech, M.",
        journal: "Measurement Science Technology",
        volume: "23",
        issue: null,
        year: "2012",
        pages: "105302",
        url: "#",
        keywords: [15, 7, 9],
    },
    {
        title: "Spatial linear disturbances in a plane wall jet",
        authors: "Schrader, L.-U., Mavriplis, C. and Brandt, L.",
        journal: "Physics of Fluids",
        volume: "24",
        issue: null,
        year: "2012",
        pages: "054104",
        url: "#",
        keywords: [7, 8, 9, 10, 11],
    },
    {
        title: "Optimal disturbances above and upstream of a flat plate with an elliptic leading edge",
        authors:
            "Monokrousos, A., Brandt, L., Mavriplis, C., and Henningson, D.S.",
        journal: "Theoretical and Computational Fluid Dynamics",
        volume: "28",
        issue: "2",
        year: "2012",
        pages: "147-157",
        url: "#",
        keywords: [7, 8, 9, 10, 11],
    },
    {
        title: "Receptivity to Free-Stream Vorticity of Flow Past a Flat Plate with Elliptic Leading Edge",
        authors:
            "Schrader, L.-U., Brandt, L., Mavriplis, C. and Henningson, D.",
        journal: "Journal of Fluid Mechanics",
        volume: "653",
        issue: null,
        year: "2010",
        pages: "245-271",
        url: "#",
        keywords: [7, 8, 9, 10, 11],
    },
    {
        title: "Mind the Gap: Women in STEM Career Breaks",
        authors:
            "Mavriplis, C., Heller, R., Yassinskaya, N., Dam, K., Shaw, M., Beil, C., Sorensen, C.",
        journal: "Journal of Technology Management and Innovation",
        volume: "5",
        issue: "1",
        year: "2010",
        pages: "140-151",
        url: "#",
        keywords: [1, 2, 3, 4, 5, 6],
    },
];

const journalIssues = [
    {
        title: "Special Issue on Interdisciplinary CFD",
        authors: "Mavriplis, C.",
        journal: "International Journal of Computational Fluid Dynamics",
        volume: "26",
        issue: "6-10",
        year: "2012",
        pages: "101",
        editors: "Mavriplis, C.",
        publisher: "Taylor & Francis",
        url: "#",
        keywords: [7, 9, 10],
    },
];

const books = [
    {
        title: "FORWARD to Professorship in STEM: Inclusive Faculty Development Strategies That Work",
        authors: "Heller, R.S., Mavriplis, C. and Sabila, P.S.",
        edition: "1",
        year: "2016",
        pages: "419",
        editors: "co-author and co-editor with Heller and Sabila",
        publisher: "Elsevier",
        address: "United States Boston",
        keywords: [2, 4, 5],
    },
];

const bookChapters = [
    {
        authors: "Mujawamariya, D., Boucher, M. et Mavriplis, C.",
        title: "Comment intéresser les filles aux STIM ? Ce que peuvent faire les parents et le personnel enseignant",
        book: "Des actions pédagogiques pour guider les filles et les femmes en STIM: Sciences, technos, ingénierie et maths",
        pages: "91-102",
        publisher: "Publication de l'Université du Québec",
        year: "2014",
        editors: "Roy, A., Mujawamariya, D., et Lafortune, L.",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        authors: "Mavriplis, C. et Davidson, V.",
        title: "GÉNIales les filles! Un programme de sensibilisation des filles au secondaire et de leurs parents",
        book: "Des actions pédagogiques pour guider les filles et les femmes en STIM: Sciences, technos, ingénierie et maths",
        pages: "103-115",
        publisher: "Publication de l'Université du Québec",
        year: "2014",
        editors: "Roy, A., Mujawamariya, D., et Lafortune, L.",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        authors: "Mavriplis, C., Heller, R. and Sorensen, C.",
        title: "The FORWARD Program",
        book: "Girls and Women in STEM: A Never-Ending Story",
        pages: "217-235",
        publisher: "Information Age Publishing",
        year: "2013",
        editors: "Koch, J. Irby, B. and Polnick, B.",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        authors: "Mavriplis, C., Heller, R. and Sorensen, C.",
        title: "FORWARD to Professorship: Academic Mentoring for for Women and Deaf Scientists",
        book: "The Diversity Mentoring Case Book",
        pages: "53-59",
        publisher: "McGraw Hill",
        year: "2012",
        editors: "Clutterbuck, D. and Poulsen, K. M.",
        keywords: [1, 2, 3, 4, 5, 6],
    },
    {
        authors: "Bujaki, M., Lennox Terrion, J., Mavriplis, C. and Moreau-Johnson, F.",
        title: "Group Mentoring Programme for Mid-Career Women Associate Professors",
        book: "The Diversity Mentoring Case Book",
        pages: "76-82",
        publisher: "McGraw Hill",
        year: "2012",
        editors: "Clutterbuck, D. and Poulsen, K. M.",
        keywords: [1, 2, 3, 4, 5, 6],
    },
];

const keywords = {
    1: "Entrepreneurship",
    2: "Gender, Work, and Family",
    3: "History of Women in Business",
    4: "Leadership",
    5: "Minorities and Education",
    6: "Science Education",
    7: "Fluid Mechanics",
    8: "Mathematical Analysis",
    9: "Mechanical Engineering",
    10: "Mordelization and Simulation",
    11: "Turbulence",
    12: "Mathmetical Analysis",
    13: "Numerical Analysis",
    14: "Software(Tools)",
    15: "Biomedical Engineering",
};

export { journalArticles, keywords, journalIssues, books, bookChapters };
